//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Hawaiian.Input
{
    public partial class @PlayerAction : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerAction()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""4264f4dd-862a-4b85-8b12-d4b5e5217042"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""04dea6c0-e35f-4372-bcc9-0445bc0c4b0c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CharacterSelect"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e0e65e3a-9571-49c0-b525-9c627abab01a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionA"",
                    ""type"": ""Value"",
                    ""id"": ""eb5fc80f-30ab-4fa0-820b-d1b30b590205"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActionB"",
                    ""type"": ""Value"",
                    ""id"": ""c9d8cb36-0efd-4faa-a1fa-08fa3a086fb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""9d47aa4d-ebd0-434d-802c-5a147074f06b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""260d9465-e576-44d6-b34c-3eaedb8b6399"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""InvLeft"",
                    ""type"": ""Button"",
                    ""id"": ""b8f84ea5-8090-4a62-a950-0358aad2d429"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InvParse"",
                    ""type"": ""Value"",
                    ""id"": ""eb9009d9-a746-47f5-8024-38a635c96257"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HoldAttack"",
                    ""type"": ""Button"",
                    ""id"": ""fd863b22-3bee-4bcf-8169-3e0861cb5fe0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickUp"",
                    ""type"": ""Button"",
                    ""id"": ""5fe6fcd5-b353-4fd6-825a-dbe46fb29b06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Parse"",
                    ""type"": ""Button"",
                    ""id"": ""3252ff69-73ab-4630-8993-d84f5b5d2a36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveCursor"",
                    ""type"": ""Value"",
                    ""id"": ""18a10a16-bed1-44c5-88e0-13fe5a732231"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""3b38de02-c033-4c49-a115-ce44b0c2fd04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""eae77aa8-94c9-4a1d-aa15-7e7778d5cb6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ParseOne"",
                    ""type"": ""Button"",
                    ""id"": ""a9bbbc5f-a5e0-4d3b-b829-cde1d48cd109"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ParseTwo"",
                    ""type"": ""Button"",
                    ""id"": ""3c055b96-da76-473d-8b2d-368c4506853d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ParseThree"",
                    ""type"": ""Button"",
                    ""id"": ""8a3e2be3-072b-4cf8-bbb6-aca6eef1dd92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ParseFour"",
                    ""type"": ""Button"",
                    ""id"": ""cbba4dab-4f11-4e8e-a37e-c2508e5b78b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ParseFive"",
                    ""type"": ""Button"",
                    ""id"": ""66e8094e-cdb3-43c7-9ab3-3024a64caf25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fccf5e2a-da0e-477c-8cf8-110e5ee34dcc"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11473482-2c7b-4c60-9d6a-bcd67b7be1fd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b8550e7-ed70-4e72-8dcf-a3a61e2f3349"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70a611e1-29f1-44aa-b506-2375e399eb90"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e49416fa-f81f-4820-a088-504874099850"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0d94b88-3f0c-477d-82c4-e4c7dcdc618d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""9518770a-a6e5-484d-9439-0f67d574e2a3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e6a6597a-e09f-4307-8ce8-4c23a940bdfc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7c7b4813-87c8-487e-a68a-f55135095f69"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6d992bdf-5ce5-48f2-811b-052c63c4384c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""153c2835-66a2-4161-9074-92698ed07994"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""caa105e0-833e-42be-8c48-c6a607c05a18"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""586fdf8f-2063-41ca-9c71-25f6b299652b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c17d4ab4-e26b-4c86-80e1-504e2590b56c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bf186c40-53b4-4da3-8d87-a24f780a788a"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""026714ad-40a3-4f2b-90ad-7ebfdc440733"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7116ccf5-8c88-495c-84ae-d40d3bc1ef03"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9f22f911-88ca-402f-b51e-7d20d6cc9434"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""38c19f60-044d-4823-9a50-8a9488a999e0"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""df32dd2b-34c0-43c4-9692-8050a96c4b86"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c40d3ceb-c57b-4a46-b9cd-7d10aeb2f37e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d7a05011-5d6a-432b-b65f-554ba95f96a1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ecdabce9-4916-420b-9b77-0754142dc787"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a75af240-f082-4555-ae5c-d96f8ee6aec1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c81400a4-422d-40c0-8084-56bc0017b3e2"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b70271d-f872-444a-ba1f-d484648ed762"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6ea0a2e-ad59-4d56-a73d-c8a2c725f932"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a8f0a0b-6860-4d14-af61-538c544b3b62"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9537be8b-c34e-42c7-b8e7-b8454fd076a4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4accf85e-264f-416f-a89a-35b4dea0d8d1"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96dfb478-b942-41a7-a1cf-84ac1727f0be"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af31af3f-2fd1-476d-af1a-4b7d59203667"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69a814ab-69ea-41fd-8c3c-581eaae02e91"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e7b6dd70-e94e-4bec-93eb-879c849639e4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvParse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a2607abf-ca51-41a8-a85f-fefdb3db30e3"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""InvParse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6e2ea6a2-79bb-4913-9050-2bd489e43bfb"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""InvParse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""24118f8a-3447-480f-bf4a-51c146fa523a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvParse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9b8bc7b5-2435-49c0-bf1c-01f341a3da9c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad;Gamepad2;Gamepad3;Gamepad4"",
                    ""action"": ""InvParse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c11a4f96-413d-45f6-afef-000cb153c47b"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""InvParse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e14e3f7b-6902-49ce-8bfe-c83bb7251bcc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""HoldAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2aa1107e-e45f-450e-bb7e-e55819db4069"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""HoldAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13851023-4a0d-43f1-be6c-61966182e3d3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""HoldAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e53eb43a-7dde-462e-981f-181c34c78e25"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b844866-dd44-49a2-ae31-08381ee9076f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5f8a81cf-d134-4ac8-8468-afcffbcd79a8"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Parse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fe0b3698-8c23-415a-91b1-a3c853dd98f2"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad;Gamepad2;Gamepad3;Gamepad4"",
                    ""action"": ""Parse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""227af2a3-5837-427e-8d95-e9ff2443ea74"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad;Gamepad2;Gamepad3;Gamepad4"",
                    ""action"": ""Parse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""75e4d870-56fa-4902-91c8-b54f6e3e467e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Parse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""064fb6dc-ee3b-4401-a09e-ac6c64ca048a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad;Gamepad2;Gamepad3;Gamepad4"",
                    ""action"": ""Parse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4b30df90-93c6-4854-8f78-f9c6766cab32"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad;Gamepad2;Gamepad3;Gamepad4"",
                    ""action"": ""Parse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""MoveCursor"",
                    ""id"": ""c7f19130-e1db-4b49-ac85-5427a0f7e7fe"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ce1c29cf-4866-4456-96ce-8f78787c5a6a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""484a45a6-bc29-4e67-94b4-fcf143ff0802"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5fc1550f-4a78-40de-8e10-a7c15de3f66e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""583fdcc8-4528-4111-b8d0-3646babca449"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b759c435-d0ba-4448-bd1c-5815f0bd9761"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75b7d6b9-e534-4a2f-8b67-7c1b9c25813e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d577a1d-3bf6-42a9-8f43-52b19d8cb261"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""831b70c1-c461-4a21-a234-3fd41c320dc3"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff20fef0-b150-43f3-88be-6ffad3b45fe6"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd22a7df-f508-456d-a547-2a54e9cf3666"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""39e065e7-0447-4b50-a8a8-e395ff888f42"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""10ce5fc6-9231-4a4f-a5c2-08ddf02335bf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""8af3bb40-aba9-4ed2-91e8-1220221b68fe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""82c0bdf0-6832-4a55-b8b6-17c5dd9cd36c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""5eb43c3d-c872-412d-a0b6-f207bfdde26e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""1c4e91d4-81b5-4042-b1b1-0dcdcf32ef84"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""D-Pad"",
                    ""id"": ""8f56d2ff-583e-4be9-bae3-cb60f10f7338"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""9888cd12-c451-42de-bd15-dd73f4232af8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""cd0de5b4-f275-49bf-9afc-4ecb97990688"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CharacterSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2045dab0-248b-48ae-92b4-1ae2a365cb5b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ParseOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df355a3b-3023-4004-aa69-3b2d5ff3bec9"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ParseTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dbc362c-3cde-47c5-96c6-6f2f0b119ec1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ParseThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea3bb40b-5dda-4095-aaed-09326c6f5bba"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ParseFour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23f36895-da63-4e79-ad9e-efe199d158c9"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ParseFive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Lobby Player"",
            ""id"": ""3bc01c39-4d9c-4138-8e68-b8d0bd7a5e74"",
            ""actions"": [
                {
                    ""name"": ""Ready"",
                    ""type"": ""Button"",
                    ""id"": ""6313d96c-bf06-4f98-afeb-950ceebcde40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""a4e85f39-9e16-49f8-82a5-9809a8c2eee7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""e02bc53f-7606-4d85-9d2e-036af7dd8d66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddBot"",
                    ""type"": ""Button"",
                    ""id"": ""300f2ece-fe16-40b7-b6d8-b2d6231cdbcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveBot"",
                    ""type"": ""Button"",
                    ""id"": ""f99a9359-81ed-484c-8e86-6a2f4fcdb5b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""193836c7-1897-4b50-83b4-aff29ce8cbb1"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6096586d-9920-4514-a12d-baf2f98cae18"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b9e51cf-265e-42d2-8dba-96909847ef8e"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfa31c99-26d6-4fa0-924b-102bbacf1036"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f90be4a-f7e0-43df-b593-62d20b7a4895"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41a4e5d3-d029-457a-86c1-3b08771e8f49"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e649e1a1-0137-4e5f-be76-cf556bf18059"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da40be0e-7644-4432-a553-e71ec9b877d6"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83edb2a1-e431-4806-a5d2-951888e4c73d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78f02067-71d1-4c81-a57f-29e8262832f5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6536ada8-8f34-4d9a-97c3-152a98c837ba"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19f673aa-9498-4d1e-a3a8-0ff9e1411a8c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a72e5ce4-51c0-44c8-99df-7636a5390b39"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59aa0545-5f6b-418f-be6a-83faf3646a46"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d2cc09c-585b-4719-9dfb-964360d64a9c"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d7bad5f-4ebd-4186-a2cb-97d4c452fbf1"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""AddBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c7036cb-2cb6-4b55-8e8d-46310eb1a0d6"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""AddBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4d5982a-7d01-4c8b-a1fc-6f078a0c86b5"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""AddBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d4883e6-0915-44e3-ad5f-c473d1b9a402"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard1"",
            ""bindingGroup"": ""Keyboard1"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard2"",
            ""bindingGroup"": ""Keyboard2"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad2"",
            ""bindingGroup"": ""Gamepad2"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad3"",
            ""bindingGroup"": ""Gamepad3"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad4"",
            ""bindingGroup"": ""Gamepad4"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard3"",
            ""bindingGroup"": ""Keyboard3"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard4"",
            ""bindingGroup"": ""Keyboard4"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_CharacterSelect = m_Player.FindAction("CharacterSelect", throwIfNotFound: true);
            m_Player_ActionA = m_Player.FindAction("ActionA", throwIfNotFound: true);
            m_Player_ActionB = m_Player.FindAction("ActionB", throwIfNotFound: true);
            m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
            m_Player_Rotate = m_Player.FindAction("Rotate", throwIfNotFound: true);
            m_Player_InvLeft = m_Player.FindAction("InvLeft", throwIfNotFound: true);
            m_Player_InvParse = m_Player.FindAction("InvParse", throwIfNotFound: true);
            m_Player_HoldAttack = m_Player.FindAction("HoldAttack", throwIfNotFound: true);
            m_Player_PickUp = m_Player.FindAction("PickUp", throwIfNotFound: true);
            m_Player_Parse = m_Player.FindAction("Parse", throwIfNotFound: true);
            m_Player_MoveCursor = m_Player.FindAction("MoveCursor", throwIfNotFound: true);
            m_Player_Drop = m_Player.FindAction("Drop", throwIfNotFound: true);
            m_Player_Menu = m_Player.FindAction("Menu", throwIfNotFound: true);
            m_Player_ParseOne = m_Player.FindAction("ParseOne", throwIfNotFound: true);
            m_Player_ParseTwo = m_Player.FindAction("ParseTwo", throwIfNotFound: true);
            m_Player_ParseThree = m_Player.FindAction("ParseThree", throwIfNotFound: true);
            m_Player_ParseFour = m_Player.FindAction("ParseFour", throwIfNotFound: true);
            m_Player_ParseFive = m_Player.FindAction("ParseFive", throwIfNotFound: true);
            // Lobby Player
            m_LobbyPlayer = asset.FindActionMap("Lobby Player", throwIfNotFound: true);
            m_LobbyPlayer_Ready = m_LobbyPlayer.FindAction("Ready", throwIfNotFound: true);
            m_LobbyPlayer_Left = m_LobbyPlayer.FindAction("Left", throwIfNotFound: true);
            m_LobbyPlayer_Right = m_LobbyPlayer.FindAction("Right", throwIfNotFound: true);
            m_LobbyPlayer_AddBot = m_LobbyPlayer.FindAction("AddBot", throwIfNotFound: true);
            m_LobbyPlayer_RemoveBot = m_LobbyPlayer.FindAction("RemoveBot", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private IPlayerActions m_PlayerActionsCallbackInterface;
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_CharacterSelect;
        private readonly InputAction m_Player_ActionA;
        private readonly InputAction m_Player_ActionB;
        private readonly InputAction m_Player_Attack;
        private readonly InputAction m_Player_Rotate;
        private readonly InputAction m_Player_InvLeft;
        private readonly InputAction m_Player_InvParse;
        private readonly InputAction m_Player_HoldAttack;
        private readonly InputAction m_Player_PickUp;
        private readonly InputAction m_Player_Parse;
        private readonly InputAction m_Player_MoveCursor;
        private readonly InputAction m_Player_Drop;
        private readonly InputAction m_Player_Menu;
        private readonly InputAction m_Player_ParseOne;
        private readonly InputAction m_Player_ParseTwo;
        private readonly InputAction m_Player_ParseThree;
        private readonly InputAction m_Player_ParseFour;
        private readonly InputAction m_Player_ParseFive;
        public struct PlayerActions
        {
            private @PlayerAction m_Wrapper;
            public PlayerActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player_Move;
            public InputAction @CharacterSelect => m_Wrapper.m_Player_CharacterSelect;
            public InputAction @ActionA => m_Wrapper.m_Player_ActionA;
            public InputAction @ActionB => m_Wrapper.m_Player_ActionB;
            public InputAction @Attack => m_Wrapper.m_Player_Attack;
            public InputAction @Rotate => m_Wrapper.m_Player_Rotate;
            public InputAction @InvLeft => m_Wrapper.m_Player_InvLeft;
            public InputAction @InvParse => m_Wrapper.m_Player_InvParse;
            public InputAction @HoldAttack => m_Wrapper.m_Player_HoldAttack;
            public InputAction @PickUp => m_Wrapper.m_Player_PickUp;
            public InputAction @Parse => m_Wrapper.m_Player_Parse;
            public InputAction @MoveCursor => m_Wrapper.m_Player_MoveCursor;
            public InputAction @Drop => m_Wrapper.m_Player_Drop;
            public InputAction @Menu => m_Wrapper.m_Player_Menu;
            public InputAction @ParseOne => m_Wrapper.m_Player_ParseOne;
            public InputAction @ParseTwo => m_Wrapper.m_Player_ParseTwo;
            public InputAction @ParseThree => m_Wrapper.m_Player_ParseThree;
            public InputAction @ParseFour => m_Wrapper.m_Player_ParseFour;
            public InputAction @ParseFive => m_Wrapper.m_Player_ParseFive;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @CharacterSelect.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharacterSelect;
                    @CharacterSelect.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharacterSelect;
                    @CharacterSelect.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharacterSelect;
                    @ActionA.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionA;
                    @ActionA.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionA;
                    @ActionA.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionA;
                    @ActionB.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionB;
                    @ActionB.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionB;
                    @ActionB.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionB;
                    @Attack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                    @Attack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                    @Attack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                    @Rotate.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotate;
                    @Rotate.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotate;
                    @Rotate.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotate;
                    @InvLeft.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvLeft;
                    @InvLeft.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvLeft;
                    @InvLeft.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvLeft;
                    @InvParse.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvParse;
                    @InvParse.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvParse;
                    @InvParse.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvParse;
                    @HoldAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                    @HoldAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                    @HoldAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                    @PickUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                    @PickUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                    @PickUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                    @Parse.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParse;
                    @Parse.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParse;
                    @Parse.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParse;
                    @MoveCursor.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveCursor;
                    @MoveCursor.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveCursor;
                    @MoveCursor.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveCursor;
                    @Drop.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop;
                    @Drop.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop;
                    @Drop.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop;
                    @Menu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
                    @Menu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
                    @Menu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
                    @ParseOne.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseOne;
                    @ParseOne.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseOne;
                    @ParseOne.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseOne;
                    @ParseTwo.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseTwo;
                    @ParseTwo.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseTwo;
                    @ParseTwo.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseTwo;
                    @ParseThree.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseThree;
                    @ParseThree.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseThree;
                    @ParseThree.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseThree;
                    @ParseFour.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseFour;
                    @ParseFour.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseFour;
                    @ParseFour.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseFour;
                    @ParseFive.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseFive;
                    @ParseFive.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseFive;
                    @ParseFive.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParseFive;
                }
                m_Wrapper.m_PlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @CharacterSelect.started += instance.OnCharacterSelect;
                    @CharacterSelect.performed += instance.OnCharacterSelect;
                    @CharacterSelect.canceled += instance.OnCharacterSelect;
                    @ActionA.started += instance.OnActionA;
                    @ActionA.performed += instance.OnActionA;
                    @ActionA.canceled += instance.OnActionA;
                    @ActionB.started += instance.OnActionB;
                    @ActionB.performed += instance.OnActionB;
                    @ActionB.canceled += instance.OnActionB;
                    @Attack.started += instance.OnAttack;
                    @Attack.performed += instance.OnAttack;
                    @Attack.canceled += instance.OnAttack;
                    @Rotate.started += instance.OnRotate;
                    @Rotate.performed += instance.OnRotate;
                    @Rotate.canceled += instance.OnRotate;
                    @InvLeft.started += instance.OnInvLeft;
                    @InvLeft.performed += instance.OnInvLeft;
                    @InvLeft.canceled += instance.OnInvLeft;
                    @InvParse.started += instance.OnInvParse;
                    @InvParse.performed += instance.OnInvParse;
                    @InvParse.canceled += instance.OnInvParse;
                    @HoldAttack.started += instance.OnHoldAttack;
                    @HoldAttack.performed += instance.OnHoldAttack;
                    @HoldAttack.canceled += instance.OnHoldAttack;
                    @PickUp.started += instance.OnPickUp;
                    @PickUp.performed += instance.OnPickUp;
                    @PickUp.canceled += instance.OnPickUp;
                    @Parse.started += instance.OnParse;
                    @Parse.performed += instance.OnParse;
                    @Parse.canceled += instance.OnParse;
                    @MoveCursor.started += instance.OnMoveCursor;
                    @MoveCursor.performed += instance.OnMoveCursor;
                    @MoveCursor.canceled += instance.OnMoveCursor;
                    @Drop.started += instance.OnDrop;
                    @Drop.performed += instance.OnDrop;
                    @Drop.canceled += instance.OnDrop;
                    @Menu.started += instance.OnMenu;
                    @Menu.performed += instance.OnMenu;
                    @Menu.canceled += instance.OnMenu;
                    @ParseOne.started += instance.OnParseOne;
                    @ParseOne.performed += instance.OnParseOne;
                    @ParseOne.canceled += instance.OnParseOne;
                    @ParseTwo.started += instance.OnParseTwo;
                    @ParseTwo.performed += instance.OnParseTwo;
                    @ParseTwo.canceled += instance.OnParseTwo;
                    @ParseThree.started += instance.OnParseThree;
                    @ParseThree.performed += instance.OnParseThree;
                    @ParseThree.canceled += instance.OnParseThree;
                    @ParseFour.started += instance.OnParseFour;
                    @ParseFour.performed += instance.OnParseFour;
                    @ParseFour.canceled += instance.OnParseFour;
                    @ParseFive.started += instance.OnParseFive;
                    @ParseFive.performed += instance.OnParseFive;
                    @ParseFive.canceled += instance.OnParseFive;
                }
            }
        }
        public PlayerActions @Player => new PlayerActions(this);

        // Lobby Player
        private readonly InputActionMap m_LobbyPlayer;
        private ILobbyPlayerActions m_LobbyPlayerActionsCallbackInterface;
        private readonly InputAction m_LobbyPlayer_Ready;
        private readonly InputAction m_LobbyPlayer_Left;
        private readonly InputAction m_LobbyPlayer_Right;
        private readonly InputAction m_LobbyPlayer_AddBot;
        private readonly InputAction m_LobbyPlayer_RemoveBot;
        public struct LobbyPlayerActions
        {
            private @PlayerAction m_Wrapper;
            public LobbyPlayerActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @Ready => m_Wrapper.m_LobbyPlayer_Ready;
            public InputAction @Left => m_Wrapper.m_LobbyPlayer_Left;
            public InputAction @Right => m_Wrapper.m_LobbyPlayer_Right;
            public InputAction @AddBot => m_Wrapper.m_LobbyPlayer_AddBot;
            public InputAction @RemoveBot => m_Wrapper.m_LobbyPlayer_RemoveBot;
            public InputActionMap Get() { return m_Wrapper.m_LobbyPlayer; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LobbyPlayerActions set) { return set.Get(); }
            public void SetCallbacks(ILobbyPlayerActions instance)
            {
                if (m_Wrapper.m_LobbyPlayerActionsCallbackInterface != null)
                {
                    @Ready.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnReady;
                    @Ready.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnReady;
                    @Ready.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnReady;
                    @Left.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnLeft;
                    @Left.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnLeft;
                    @Left.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnLeft;
                    @Right.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRight;
                    @Right.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRight;
                    @Right.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRight;
                    @AddBot.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnAddBot;
                    @AddBot.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnAddBot;
                    @AddBot.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnAddBot;
                    @RemoveBot.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRemoveBot;
                    @RemoveBot.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRemoveBot;
                    @RemoveBot.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRemoveBot;
                }
                m_Wrapper.m_LobbyPlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Ready.started += instance.OnReady;
                    @Ready.performed += instance.OnReady;
                    @Ready.canceled += instance.OnReady;
                    @Left.started += instance.OnLeft;
                    @Left.performed += instance.OnLeft;
                    @Left.canceled += instance.OnLeft;
                    @Right.started += instance.OnRight;
                    @Right.performed += instance.OnRight;
                    @Right.canceled += instance.OnRight;
                    @AddBot.started += instance.OnAddBot;
                    @AddBot.performed += instance.OnAddBot;
                    @AddBot.canceled += instance.OnAddBot;
                    @RemoveBot.started += instance.OnRemoveBot;
                    @RemoveBot.performed += instance.OnRemoveBot;
                    @RemoveBot.canceled += instance.OnRemoveBot;
                }
            }
        }
        public LobbyPlayerActions @LobbyPlayer => new LobbyPlayerActions(this);
        private int m_Keyboard1SchemeIndex = -1;
        public InputControlScheme Keyboard1Scheme
        {
            get
            {
                if (m_Keyboard1SchemeIndex == -1) m_Keyboard1SchemeIndex = asset.FindControlSchemeIndex("Keyboard1");
                return asset.controlSchemes[m_Keyboard1SchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        private int m_Keyboard2SchemeIndex = -1;
        public InputControlScheme Keyboard2Scheme
        {
            get
            {
                if (m_Keyboard2SchemeIndex == -1) m_Keyboard2SchemeIndex = asset.FindControlSchemeIndex("Keyboard2");
                return asset.controlSchemes[m_Keyboard2SchemeIndex];
            }
        }
        private int m_Gamepad2SchemeIndex = -1;
        public InputControlScheme Gamepad2Scheme
        {
            get
            {
                if (m_Gamepad2SchemeIndex == -1) m_Gamepad2SchemeIndex = asset.FindControlSchemeIndex("Gamepad2");
                return asset.controlSchemes[m_Gamepad2SchemeIndex];
            }
        }
        private int m_Gamepad3SchemeIndex = -1;
        public InputControlScheme Gamepad3Scheme
        {
            get
            {
                if (m_Gamepad3SchemeIndex == -1) m_Gamepad3SchemeIndex = asset.FindControlSchemeIndex("Gamepad3");
                return asset.controlSchemes[m_Gamepad3SchemeIndex];
            }
        }
        private int m_Gamepad4SchemeIndex = -1;
        public InputControlScheme Gamepad4Scheme
        {
            get
            {
                if (m_Gamepad4SchemeIndex == -1) m_Gamepad4SchemeIndex = asset.FindControlSchemeIndex("Gamepad4");
                return asset.controlSchemes[m_Gamepad4SchemeIndex];
            }
        }
        private int m_Keyboard3SchemeIndex = -1;
        public InputControlScheme Keyboard3Scheme
        {
            get
            {
                if (m_Keyboard3SchemeIndex == -1) m_Keyboard3SchemeIndex = asset.FindControlSchemeIndex("Keyboard3");
                return asset.controlSchemes[m_Keyboard3SchemeIndex];
            }
        }
        private int m_Keyboard4SchemeIndex = -1;
        public InputControlScheme Keyboard4Scheme
        {
            get
            {
                if (m_Keyboard4SchemeIndex == -1) m_Keyboard4SchemeIndex = asset.FindControlSchemeIndex("Keyboard4");
                return asset.controlSchemes[m_Keyboard4SchemeIndex];
            }
        }
        public interface IPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnCharacterSelect(InputAction.CallbackContext context);
            void OnActionA(InputAction.CallbackContext context);
            void OnActionB(InputAction.CallbackContext context);
            void OnAttack(InputAction.CallbackContext context);
            void OnRotate(InputAction.CallbackContext context);
            void OnInvLeft(InputAction.CallbackContext context);
            void OnInvParse(InputAction.CallbackContext context);
            void OnHoldAttack(InputAction.CallbackContext context);
            void OnPickUp(InputAction.CallbackContext context);
            void OnParse(InputAction.CallbackContext context);
            void OnMoveCursor(InputAction.CallbackContext context);
            void OnDrop(InputAction.CallbackContext context);
            void OnMenu(InputAction.CallbackContext context);
            void OnParseOne(InputAction.CallbackContext context);
            void OnParseTwo(InputAction.CallbackContext context);
            void OnParseThree(InputAction.CallbackContext context);
            void OnParseFour(InputAction.CallbackContext context);
            void OnParseFive(InputAction.CallbackContext context);
        }
        public interface ILobbyPlayerActions
        {
            void OnReady(InputAction.CallbackContext context);
            void OnLeft(InputAction.CallbackContext context);
            void OnRight(InputAction.CallbackContext context);
            void OnAddBot(InputAction.CallbackContext context);
            void OnRemoveBot(InputAction.CallbackContext context);
        }
    }
}
