//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Hawaiian.Input
{
    public partial class @PlayerAction : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerAction()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""4264f4dd-862a-4b85-8b12-d4b5e5217042"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""04dea6c0-e35f-4372-bcc9-0445bc0c4b0c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionA"",
                    ""type"": ""Value"",
                    ""id"": ""eb5fc80f-30ab-4fa0-820b-d1b30b590205"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActionB"",
                    ""type"": ""Value"",
                    ""id"": ""c9d8cb36-0efd-4faa-a1fa-08fa3a086fb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""9d47aa4d-ebd0-434d-802c-5a147074f06b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""260d9465-e576-44d6-b34c-3eaedb8b6399"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""InvLeft"",
                    ""type"": ""Button"",
                    ""id"": ""b8f84ea5-8090-4a62-a950-0358aad2d429"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InvParse"",
                    ""type"": ""Button"",
                    ""id"": ""eb9009d9-a746-47f5-8024-38a635c96257"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldAttack"",
                    ""type"": ""Button"",
                    ""id"": ""fd863b22-3bee-4bcf-8169-3e0861cb5fe0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickUp"",
                    ""type"": ""Button"",
                    ""id"": ""5fe6fcd5-b353-4fd6-825a-dbe46fb29b06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fccf5e2a-da0e-477c-8cf8-110e5ee34dcc"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11473482-2c7b-4c60-9d6a-bcd67b7be1fd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b8550e7-ed70-4e72-8dcf-a3a61e2f3349"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70a611e1-29f1-44aa-b506-2375e399eb90"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e49416fa-f81f-4820-a088-504874099850"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ActionA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""9518770a-a6e5-484d-9439-0f67d574e2a3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e6a6597a-e09f-4307-8ce8-4c23a940bdfc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6d992bdf-5ce5-48f2-811b-052c63c4384c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7c7b4813-87c8-487e-a68a-f55135095f69"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""153c2835-66a2-4161-9074-92698ed07994"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""caa105e0-833e-42be-8c48-c6a607c05a18"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""586fdf8f-2063-41ca-9c71-25f6b299652b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c17d4ab4-e26b-4c86-80e1-504e2590b56c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bf186c40-53b4-4da3-8d87-a24f780a788a"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""026714ad-40a3-4f2b-90ad-7ebfdc440733"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7116ccf5-8c88-495c-84ae-d40d3bc1ef03"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d0d94b88-3f0c-477d-82c4-e4c7dcdc618d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9f22f911-88ca-402f-b51e-7d20d6cc9434"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""38c19f60-044d-4823-9a50-8a9488a999e0"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""df32dd2b-34c0-43c4-9692-8050a96c4b86"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c40d3ceb-c57b-4a46-b9cd-7d10aeb2f37e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d7a05011-5d6a-432b-b65f-554ba95f96a1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ecdabce9-4916-420b-9b77-0754142dc787"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a75af240-f082-4555-ae5c-d96f8ee6aec1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c81400a4-422d-40c0-8084-56bc0017b3e2"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b70271d-f872-444a-ba1f-d484648ed762"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6ea0a2e-ad59-4d56-a73d-c8a2c725f932"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ActionB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9537be8b-c34e-42c7-b8e7-b8454fd076a4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4accf85e-264f-416f-a89a-35b4dea0d8d1"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a8f0a0b-6860-4d14-af61-538c544b3b62"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96dfb478-b942-41a7-a1cf-84ac1727f0be"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af31af3f-2fd1-476d-af1a-4b7d59203667"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e7b6dd70-e94e-4bec-93eb-879c849639e4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvParse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6e2ea6a2-79bb-4913-9050-2bd489e43bfb"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvParse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a2607abf-ca51-41a8-a85f-fefdb3db30e3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvParse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e14e3f7b-6902-49ce-8bfe-c83bb7251bcc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""HoldAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2aa1107e-e45f-450e-bb7e-e55819db4069"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""HoldAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13851023-4a0d-43f1-be6c-61966182e3d3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""HoldAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e53eb43a-7dde-462e-981f-181c34c78e25"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b844866-dd44-49a2-ae31-08381ee9076f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Lobby Player"",
            ""id"": ""3bc01c39-4d9c-4138-8e68-b8d0bd7a5e74"",
            ""actions"": [
                {
                    ""name"": ""Ready"",
                    ""type"": ""Button"",
                    ""id"": ""6313d96c-bf06-4f98-afeb-950ceebcde40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""a4e85f39-9e16-49f8-82a5-9809a8c2eee7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""e02bc53f-7606-4d85-9d2e-036af7dd8d66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddBot"",
                    ""type"": ""Button"",
                    ""id"": ""300f2ece-fe16-40b7-b6d8-b2d6231cdbcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveBot"",
                    ""type"": ""Button"",
                    ""id"": ""f99a9359-81ed-484c-8e86-6a2f4fcdb5b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""193836c7-1897-4b50-83b4-aff29ce8cbb1"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6096586d-9920-4514-a12d-baf2f98cae18"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b9e51cf-265e-42d2-8dba-96909847ef8e"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfa31c99-26d6-4fa0-924b-102bbacf1036"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f90be4a-f7e0-43df-b593-62d20b7a4895"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41a4e5d3-d029-457a-86c1-3b08771e8f49"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e649e1a1-0137-4e5f-be76-cf556bf18059"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da40be0e-7644-4432-a553-e71ec9b877d6"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83edb2a1-e431-4806-a5d2-951888e4c73d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Ready"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78f02067-71d1-4c81-a57f-29e8262832f5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6536ada8-8f34-4d9a-97c3-152a98c837ba"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19f673aa-9498-4d1e-a3a8-0ff9e1411a8c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a72e5ce4-51c0-44c8-99df-7636a5390b39"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59aa0545-5f6b-418f-be6a-83faf3646a46"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d2cc09c-585b-4719-9dfb-964360d64a9c"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d7bad5f-4ebd-4186-a2cb-97d4c452fbf1"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard1"",
                    ""action"": ""AddBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c7036cb-2cb6-4b55-8e8d-46310eb1a0d6"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""AddBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4d5982a-7d01-4c8b-a1fc-6f078a0c86b5"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard2"",
                    ""action"": ""AddBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d4883e6-0915-44e3-ad5f-c473d1b9a402"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard1"",
            ""bindingGroup"": ""Keyboard1"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard2"",
            ""bindingGroup"": ""Keyboard2"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_ActionA = m_Player.FindAction("ActionA", throwIfNotFound: true);
            m_Player_ActionB = m_Player.FindAction("ActionB", throwIfNotFound: true);
            m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
            m_Player_Rotate = m_Player.FindAction("Rotate", throwIfNotFound: true);
            m_Player_InvLeft = m_Player.FindAction("InvLeft", throwIfNotFound: true);
            m_Player_InvParse = m_Player.FindAction("InvParse", throwIfNotFound: true);
            m_Player_HoldAttack = m_Player.FindAction("HoldAttack", throwIfNotFound: true);
            m_Player_PickUp = m_Player.FindAction("PickUp", throwIfNotFound: true);
            // Lobby Player
            m_LobbyPlayer = asset.FindActionMap("Lobby Player", throwIfNotFound: true);
            m_LobbyPlayer_Ready = m_LobbyPlayer.FindAction("Ready", throwIfNotFound: true);
            m_LobbyPlayer_Left = m_LobbyPlayer.FindAction("Left", throwIfNotFound: true);
            m_LobbyPlayer_Right = m_LobbyPlayer.FindAction("Right", throwIfNotFound: true);
            m_LobbyPlayer_AddBot = m_LobbyPlayer.FindAction("AddBot", throwIfNotFound: true);
            m_LobbyPlayer_RemoveBot = m_LobbyPlayer.FindAction("RemoveBot", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private IPlayerActions m_PlayerActionsCallbackInterface;
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_ActionA;
        private readonly InputAction m_Player_ActionB;
        private readonly InputAction m_Player_Attack;
        private readonly InputAction m_Player_Rotate;
        private readonly InputAction m_Player_InvLeft;
        private readonly InputAction m_Player_InvParse;
        private readonly InputAction m_Player_HoldAttack;
        private readonly InputAction m_Player_PickUp;
        public struct PlayerActions
        {
            private @PlayerAction m_Wrapper;
            public PlayerActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player_Move;
            public InputAction @ActionA => m_Wrapper.m_Player_ActionA;
            public InputAction @ActionB => m_Wrapper.m_Player_ActionB;
            public InputAction @Attack => m_Wrapper.m_Player_Attack;
            public InputAction @Rotate => m_Wrapper.m_Player_Rotate;
            public InputAction @InvLeft => m_Wrapper.m_Player_InvLeft;
            public InputAction @InvParse => m_Wrapper.m_Player_InvParse;
            public InputAction @HoldAttack => m_Wrapper.m_Player_HoldAttack;
            public InputAction @PickUp => m_Wrapper.m_Player_PickUp;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @ActionA.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionA;
                    @ActionA.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionA;
                    @ActionA.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionA;
                    @ActionB.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionB;
                    @ActionB.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionB;
                    @ActionB.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnActionB;
                    @Attack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                    @Attack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                    @Attack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                    @Rotate.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotate;
                    @Rotate.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotate;
                    @Rotate.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotate;
                    @InvLeft.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvLeft;
                    @InvLeft.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvLeft;
                    @InvLeft.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvLeft;
                    @InvParse.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvParse;
                    @InvParse.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvParse;
                    @InvParse.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInvParse;
                    @HoldAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                    @HoldAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                    @HoldAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                    @PickUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                    @PickUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                    @PickUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                }
                m_Wrapper.m_PlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @ActionA.started += instance.OnActionA;
                    @ActionA.performed += instance.OnActionA;
                    @ActionA.canceled += instance.OnActionA;
                    @ActionB.started += instance.OnActionB;
                    @ActionB.performed += instance.OnActionB;
                    @ActionB.canceled += instance.OnActionB;
                    @Attack.started += instance.OnAttack;
                    @Attack.performed += instance.OnAttack;
                    @Attack.canceled += instance.OnAttack;
                    @Rotate.started += instance.OnRotate;
                    @Rotate.performed += instance.OnRotate;
                    @Rotate.canceled += instance.OnRotate;
                    @InvLeft.started += instance.OnInvLeft;
                    @InvLeft.performed += instance.OnInvLeft;
                    @InvLeft.canceled += instance.OnInvLeft;
                    @InvParse.started += instance.OnInvParse;
                    @InvParse.performed += instance.OnInvParse;
                    @InvParse.canceled += instance.OnInvParse;
                    @HoldAttack.started += instance.OnHoldAttack;
                    @HoldAttack.performed += instance.OnHoldAttack;
                    @HoldAttack.canceled += instance.OnHoldAttack;
                    @PickUp.started += instance.OnPickUp;
                    @PickUp.performed += instance.OnPickUp;
                    @PickUp.canceled += instance.OnPickUp;
                }
            }
        }
        public PlayerActions @Player => new PlayerActions(this);

        // Lobby Player
        private readonly InputActionMap m_LobbyPlayer;
        private ILobbyPlayerActions m_LobbyPlayerActionsCallbackInterface;
        private readonly InputAction m_LobbyPlayer_Ready;
        private readonly InputAction m_LobbyPlayer_Left;
        private readonly InputAction m_LobbyPlayer_Right;
        private readonly InputAction m_LobbyPlayer_AddBot;
        private readonly InputAction m_LobbyPlayer_RemoveBot;
        public struct LobbyPlayerActions
        {
            private @PlayerAction m_Wrapper;
            public LobbyPlayerActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @Ready => m_Wrapper.m_LobbyPlayer_Ready;
            public InputAction @Left => m_Wrapper.m_LobbyPlayer_Left;
            public InputAction @Right => m_Wrapper.m_LobbyPlayer_Right;
            public InputAction @AddBot => m_Wrapper.m_LobbyPlayer_AddBot;
            public InputAction @RemoveBot => m_Wrapper.m_LobbyPlayer_RemoveBot;
            public InputActionMap Get() { return m_Wrapper.m_LobbyPlayer; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LobbyPlayerActions set) { return set.Get(); }
            public void SetCallbacks(ILobbyPlayerActions instance)
            {
                if (m_Wrapper.m_LobbyPlayerActionsCallbackInterface != null)
                {
                    @Ready.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnReady;
                    @Ready.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnReady;
                    @Ready.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnReady;
                    @Left.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnLeft;
                    @Left.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnLeft;
                    @Left.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnLeft;
                    @Right.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRight;
                    @Right.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRight;
                    @Right.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRight;
                    @AddBot.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnAddBot;
                    @AddBot.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnAddBot;
                    @AddBot.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnAddBot;
                    @RemoveBot.started -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRemoveBot;
                    @RemoveBot.performed -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRemoveBot;
                    @RemoveBot.canceled -= m_Wrapper.m_LobbyPlayerActionsCallbackInterface.OnRemoveBot;
                }
                m_Wrapper.m_LobbyPlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Ready.started += instance.OnReady;
                    @Ready.performed += instance.OnReady;
                    @Ready.canceled += instance.OnReady;
                    @Left.started += instance.OnLeft;
                    @Left.performed += instance.OnLeft;
                    @Left.canceled += instance.OnLeft;
                    @Right.started += instance.OnRight;
                    @Right.performed += instance.OnRight;
                    @Right.canceled += instance.OnRight;
                    @AddBot.started += instance.OnAddBot;
                    @AddBot.performed += instance.OnAddBot;
                    @AddBot.canceled += instance.OnAddBot;
                    @RemoveBot.started += instance.OnRemoveBot;
                    @RemoveBot.performed += instance.OnRemoveBot;
                    @RemoveBot.canceled += instance.OnRemoveBot;
                }
            }
        }
        public LobbyPlayerActions @LobbyPlayer => new LobbyPlayerActions(this);
        private int m_Keyboard1SchemeIndex = -1;
        public InputControlScheme Keyboard1Scheme
        {
            get
            {
                if (m_Keyboard1SchemeIndex == -1) m_Keyboard1SchemeIndex = asset.FindControlSchemeIndex("Keyboard1");
                return asset.controlSchemes[m_Keyboard1SchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        private int m_Keyboard2SchemeIndex = -1;
        public InputControlScheme Keyboard2Scheme
        {
            get
            {
                if (m_Keyboard2SchemeIndex == -1) m_Keyboard2SchemeIndex = asset.FindControlSchemeIndex("Keyboard2");
                return asset.controlSchemes[m_Keyboard2SchemeIndex];
            }
        }
        public interface IPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnActionA(InputAction.CallbackContext context);
            void OnActionB(InputAction.CallbackContext context);
            void OnAttack(InputAction.CallbackContext context);
            void OnRotate(InputAction.CallbackContext context);
            void OnInvLeft(InputAction.CallbackContext context);
            void OnInvParse(InputAction.CallbackContext context);
            void OnHoldAttack(InputAction.CallbackContext context);
            void OnPickUp(InputAction.CallbackContext context);
        }
        public interface ILobbyPlayerActions
        {
            void OnReady(InputAction.CallbackContext context);
            void OnLeft(InputAction.CallbackContext context);
            void OnRight(InputAction.CallbackContext context);
            void OnAddBot(InputAction.CallbackContext context);
            void OnRemoveBot(InputAction.CallbackContext context);
        }
    }
}
